#!/bin/bash
# .ai/scripts/generate.sh
# 공통 base + 모델별 adapter + 스킬(오버라이드 우선) 을 조합하여
# 루트의 CLAUDE.md / AGENTS.md / GEMINI.md 를 생성한다.
#
# 사용법:
#   .ai/scripts/generate.sh              # 전체 생성
#   .ai/scripts/generate.sh claude       # Claude만 생성
#
# 프로젝트별 오버레이:
#   .ai-local/ 디렉토리가 있으면 해당 내용을 추가로 머지한다.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AI_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$AI_DIR/.." && pwd)"

# ── 모델 → 출력 파일 매핑 ──
declare -A MODEL_OUTPUT=(
  [claude]="CLAUDE.md"
  [codex]="AGENTS.md"
  [gemini]="GEMINI.md"
)

assemble() {
  local model=$1
  local output_file="${REPO_ROOT}/${MODEL_OUTPUT[$model]}"
  local tmp
  tmp=$(mktemp)

  # 헤더
  echo "<!-- AUTO-GENERATED by .ai/scripts/generate.sh — DO NOT EDIT DIRECTLY -->" > "$tmp"
  echo "" >> "$tmp"

  # 1) 공통 base
  cat "$AI_DIR/adapters/_base.md" >> "$tmp"
  echo -e "\n---\n" >> "$tmp"

  # 2) 모델별 preamble
  local preamble="$AI_DIR/adapters/$model/preamble.md"
  if [[ -f "$preamble" ]]; then
    cat "$preamble" >> "$tmp"
    echo -e "\n---\n" >> "$tmp"
  fi

  # 3) 스킬 본문 (오버라이드 우선)
  if [[ -d "$AI_DIR/core/skills" ]]; then
    local has_skills=false
    for skill_dir in "$AI_DIR/core/skills"/*/; do
      [[ -d "$skill_dir" ]] || continue
      local skill_name
      skill_name=$(basename "$skill_dir")
      local override="$AI_DIR/adapters/$model/overrides/${skill_name}.md"
      local core_skill="$skill_dir/skill.md"

      if [[ -f "$override" ]]; then
        if [[ "$has_skills" == false ]]; then
          echo "# 스킬 상세" >> "$tmp"
          echo "" >> "$tmp"
          has_skills=true
        fi
        echo "## $skill_name (오버라이드 적용)" >> "$tmp"
        echo "" >> "$tmp"
        cat "$override" >> "$tmp"
        echo -e "\n" >> "$tmp"
        # 본문도 포함 (오버라이드는 보충이므로)
        if [[ -f "$core_skill" ]]; then
          echo "<details><summary>공통 본문 참조</summary>" >> "$tmp"
          echo "" >> "$tmp"
          cat "$core_skill" >> "$tmp"
          echo -e "\n</details>\n" >> "$tmp"
        fi
      elif [[ -f "$core_skill" ]]; then
        if [[ "$has_skills" == false ]]; then
          echo "# 스킬 상세" >> "$tmp"
          echo "" >> "$tmp"
          has_skills=true
        fi
        echo "## $skill_name" >> "$tmp"
        echo "" >> "$tmp"
        cat "$core_skill" >> "$tmp"
        echo -e "\n" >> "$tmp"
      fi
    done
  fi

  # 4) 프로젝트별 로컬 오버레이 (.ai-local/)
  local ai_local="$REPO_ROOT/.ai-local"
  if [[ -d "$ai_local" ]]; then
    echo "---" >> "$tmp"
    echo "" >> "$tmp"
    echo "# 프로젝트 전용 규칙" >> "$tmp"
    echo "" >> "$tmp"

    # 로컬 정책
    if [[ -d "$ai_local/policies" ]]; then
      for policy in "$ai_local/policies"/*.md; do
        [[ -f "$policy" ]] || continue
        cat "$policy" >> "$tmp"
        echo -e "\n" >> "$tmp"
      done
    fi

    # 로컬 스킬
    if [[ -d "$ai_local/skills" ]]; then
      for skill_dir in "$ai_local/skills"/*/; do
        [[ -d "$skill_dir" ]] || continue
        local skill_name
        skill_name=$(basename "$skill_dir")
        local local_skill="$skill_dir/skill.md"
        if [[ -f "$local_skill" ]]; then
          echo "## $skill_name (프로젝트 전용)" >> "$tmp"
          echo "" >> "$tmp"
          cat "$local_skill" >> "$tmp"
          echo -e "\n" >> "$tmp"
        fi
      done
    fi
  fi

  mv "$tmp" "$output_file"
  echo "✓ ${MODEL_OUTPUT[$model]} 생성 완료"
}

# ── 메인 ──
if [[ $# -gt 0 ]]; then
  for model in "$@"; do
    if [[ -v "MODEL_OUTPUT[$model]" ]]; then
      assemble "$model"
    else
      echo "✗ 알 수 없는 모델: $model (claude|codex|gemini)" >&2
      exit 1
    fi
  done
else
  for model in claude codex gemini; do
    assemble "$model"
  done
fi
