#!/bin/bash
# .ai/scripts/generate.sh
# 공통 base + 모델별 adapter + 스킬(오버라이드 우선) 을 조합하여
# 루트의 CLAUDE.md / AGENTS.md / GEMINI.md 를 생성한다.
#
# 사용법:
#   .ai/scripts/generate.sh              # 전체 생성
#   .ai/scripts/generate.sh claude       # Claude만 생성
#
# 프로젝트별 오버레이:
#   .ai-local/ 디렉토리가 있으면 해당 내용을 추가로 머지한다.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
AI_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$AI_DIR/.." && pwd)"

# ── 모델 → 출력 파일 매핑 ──
declare -A MODEL_OUTPUT=(
  [claude]="CLAUDE.md"
  [codex]="AGENTS.md"
  [gemini]="GEMINI.md"
)

assemble() {
  local model=$1
  local output_file="${REPO_ROOT}/${MODEL_OUTPUT[$model]}"
  local tmp
  tmp=$(mktemp)

  # 헤더
  echo "<!-- AUTO-GENERATED by .ai/scripts/generate.sh — DO NOT EDIT DIRECTLY -->" > "$tmp"
  echo "" >> "$tmp"

  # 1) 공통 base
  cat "$AI_DIR/adapters/_base.md" >> "$tmp"
  echo -e "\n---\n" >> "$tmp"

  # 2) 모델별 preamble
  local preamble="$AI_DIR/adapters/$model/preamble.md"
  if [[ -f "$preamble" ]]; then
    cat "$preamble" >> "$tmp"
    echo -e "\n---\n" >> "$tmp"
  fi

  # 3) 스킬 참조 링크 목록 생성
  echo "## 스킬 참조" >> "$tmp"
  echo "" >> "$tmp"
  echo "작업 유형에 맞는 스킬이 있으면 아래 경로를 참조한다:" >> "$tmp"
  echo "" >> "$tmp"

  if [[ -d "$AI_DIR/core/skills" ]]; then
    for skill_dir in "$AI_DIR/core/skills"/*/; do
      [[ -d "$skill_dir" ]] || continue
      local skill_name
      skill_name=$(basename "$skill_dir")
      if [[ -f "$AI_DIR/adapters/$model/overrides/${skill_name}.md" ]]; then
        echo "- **$skill_name** — \`.ai/adapters/$model/overrides/${skill_name}.md\` (오버라이드 적용)" >> "$tmp"
      elif [[ -f "$skill_dir/skill.md" ]]; then
        echo "- **$skill_name** — \`.ai/core/skills/$skill_name/skill.md\`" >> "$tmp"
      fi
    done
  fi

  local ai_local="$REPO_ROOT/.ai-local"
  if [[ -d "$ai_local/skills" ]]; then
    for skill_dir in "$ai_local/skills"/*/; do
      [[ -d "$skill_dir" ]] || continue
      local skill_name
      skill_name=$(basename "$skill_dir")
      if [[ -f "$skill_dir/skill.md" ]]; then
        echo "- **$skill_name** — \`.ai-local/skills/$skill_name/skill.md\`" >> "$tmp"
      fi
    done
  fi
  echo "" >> "$tmp"

  # 4) 프로젝트별 로컬 오버레이 (.ai-local/policies/)
  if [[ -d "$ai_local" ]]; then
    if [[ -d "$ai_local/policies" ]]; then
      local has_policies=false
      for policy in "$ai_local/policies"/*.md; do
        [[ -f "$policy" ]] || continue
        if [[ "$has_policies" == false ]]; then
          echo "---" >> "$tmp"
          echo "" >> "$tmp"
          echo "# 프로젝트 전용 규칙" >> "$tmp"
          echo "" >> "$tmp"
          has_policies=true
        fi
        cat "$policy" >> "$tmp"
        echo -e "\n" >> "$tmp"
      done
    fi
  fi

  mv "$tmp" "$output_file"
  echo "✓ ${MODEL_OUTPUT[$model]} 생성 완료"
}

# ── 메인 ──
if [[ $# -gt 0 ]]; then
  for model in "$@"; do
    if [[ -v "MODEL_OUTPUT[$model]" ]]; then
      assemble "$model"
    else
      echo "✗ 알 수 없는 모델: $model (claude|codex|gemini)" >&2
      exit 1
    fi
  done
else
  for model in claude codex gemini; do
    assemble "$model"
  done
fi
